apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: si-site-b
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/waynedovey/service-interconnect-edb-demo
    targetRevision: main
    path: site-b
  destination:
    name: site-b
    namespace: interconnect-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
