apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: edb-app-user
  namespace: edb-demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-site-a
  target:
    name: app-user-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: site-a/edb/app-user
        property: username
    - secretKey: password
      remoteRef:
        key: site-a/edb/app-user
        property: password
