apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-site-b
spec:
  provider:
    vault:
      server: https://REPLACE_WITH_VAULT_URL
      path: ocp
      version: v2
      auth:
        kubernetes:
          mountPath: /v1/auth/kubernetes
          role: ocp-site-b
          serviceAccountRef:
            name: external-secrets-operator
            namespace: openshift-operators
